### ISSUE TITLE
No Bound Verification on `pour_size`

### ISSUE THREAD

**Issue by jsr5194** [jpecsi/kegwatch#13]
https://github.com/jpecsi/kegwatch/blob/75a889a473b685770b245c5bb087212fa4691b55/server/api/api.py#L170

Should throw in an upper and lower limit in the verification of `pour_size`

Request:

```
POST /pours/create/ HTTP/1.1
Host: localhost:25518
<snip>
Content-Type: application/json
Content-Length: 110

{
"keg_tap": 1,
"pour_size":1000000000000000000000000000000000000000000000000000,
"pour_user":"username"
}
```

Crash:

```
wmb-api  | 2024-08-09 17:15:11 [STATUS] All data passed validation
wmb-api  | ERROR:api:Exception on /pours/create/ [POST]
wmb-api  | Traceback (most recent call last):
wmb-api  |   File "/usr/local/lib/python3.11/site-packages/mysql/connector/connection_cext.py", line 705, in cmd_query
wmb-api  |     self._cmysql.query(
wmb-api  | _mysql_connector.MySQLInterfaceError: Out of range value for column 'pour_size' at row 1
wmb-api  | 
wmb-api  | The above exception was the direct cause of the following exception:
wmb-api  | 
wmb-api  | Traceback (most recent call last):
wmb-api  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
wmb-api  |     response = self.full_dispatch_request()
wmb-api  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wmb-api  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
wmb-api  |     rv = self.handle_user_exception(e)
wmb-api  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wmb-api  |   File "/usr/local/lib/python3.11/site-packages/flask_cors/extension.py", line 178, in wrapped_function
wmb-api  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
wmb-api  |                                                 ^^^^^^^^^^^^^^^^^^
wmb-api  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
wmb-api  |     rv = self.dispatch_request()
wmb-api  |          ^^^^^^^^^^^^^^^^^^^^^^^
wmb-api  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
wmb-api  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
wmb-api  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wmb-api  |   File "/app/./api.py", line 441, in post_new_pour
wmb-api  |     if (db_query(insert_sql,insert_val,1)):
wmb-api  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wmb-api  |   File "/app/./api.py", line 56, in db_query
wmb-api  |     cursor.execute(q,v)
wmb-api  |   File "/usr/local/lib/python3.11/site-packages/mysql/connector/cursor_cext.py", line 357, in execute
wmb-api  |     result = self._connection.cmd_query(
wmb-api  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
wmb-api  |   File "/usr/local/lib/python3.11/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 97, in wrapper
wmb-api  |     return method(cnx, *args, **kwargs)
wmb-api  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wmb-api  |   File "/usr/local/lib/python3.11/site-packages/mysql/connector/connection_cext.py", line 713, in cmd_query
wmb-api  |     raise get_mysql_exception(
wmb-api  | mysql.connector.errors.DataError: 1264 (22003): Out of range value for column 'pour_size' at row 1

```

**Comment by jpecsi** [comment]
Added a check in the validation function to make sure the number does not exceed 9999.9999 which is the limit for the data field
